Gemfile.lock, db/migrate/20230320083539_add_first_name_to_users.rb, db/migrate/20230320084300_add_last_name_to_users.rb, db/migrate/20230320085523_add_current_profession_to_users.rb, db/migrate/20230320085722_add_age_to_users.rb, db/migrate/20230320090601_add_null_constraints_to_users.rb, db/schema.rb
=> Adding fields to user model

app/models/career.rb, app/models/pathway.rb, app/models/programme.rb, app/models/soft_skill.rb, app/models/subject.rb, app/models/user.rb, db/migrate/20230320093226_create_programmes.rb, db/migrate/20230320093810_create_careers.rb, db/migrate/20230320094210_create_soft_skills.rb, db/migrate/20230320094341_create_subjects.rb, db/migrate/20230320094825_create_pathways.rb, db/schema.rb, pull_request_template.md, test/models/career_test.rb, test/models/pathway_test.rb, test/models/programme_test.rb, test/models/soft_skill_test.rb, test/models/subject_test.rb
Created all the models creation with associations
Please include a summary of the changes and the link to the ticket (jira/canban board etc). Please also include relevant motivation and context. List any dependencies that are required for this change.
-  [x] My code follows the style guidelines of this project
=>  models creation

config/routes.rb
Added routes 
Added routes for users, programmes, pathways and careers
=> 20 routes configuration

Gemfile.lock, app/models/career.rb, app/models/pathway.rb, app/models/programme.rb, app/models/soft_skill.rb, app/models/subject.rb, app/models/user.rb, db/migrate/20230321045412_add_name_and_summary_to_careers.rb, db/migrate/20230321050721_remove_age_add_occupation_to_users.rb, db/migrate/20230321051324_remove_description_add_responsibilities_progression_education_to_careers.rb, db/migrate/20230321064838_remove_null_false_from_first_name_last_name_occupation.rb, db/migrate/20230321073114_remove_description_add_summary_name_university_overview_to_programmes.rb, db/schema.rb
- Added validations to models.
- Removed, added and changed some fields.
- Removed some null: false
- [] I have commented my code, particularly in hard-to-understand areas
=> 18 models validation

db/migrate/20230321081624_add_join_tables.rb, db/schema.rb
Please include a summary of the changes and the link to the ticket (jira/canban board etc). Please also include relevant motivation and context. List any dependencies that are required for this change.
=> 24 add missing join tables

app/assets/stylesheets/config/_bootstrap_variables.scss, app/assets/stylesheets/config/_colors.scss, app/views/shared/_navbar.html.erb
Created navbar with appropriate styling and links. Changed default colors for future use.
=> 38 create navbar

app/assets/stylesheets/components/_footer.scss, app/assets/stylesheets/components/_index.scss, app/views/layouts/application.html.erb, app/views/shared/_footer.html.erb
Added footer with github links
=> 44 create reusable components part 1

app/assets/stylesheets/components/_form.scss, app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/config/_bootstrap_variables.scss, app/javascript/controllers/index.js, app/javascript/controllers/user_form_controller.js, app/models/user.rb, app/views/users/edit.html.erb
Styled form to be a multi-page form and to look like figma mockups.
=> 42 style form to match figma

app/assets/stylesheets/components/_index.scss, app/assets/stylesheets/components/_popup_form.scss, app/javascript/controllers/index.js, app/javascript/controllers/modal_controller.js, app/views/programmes/index.html.erb
Added modals for use in login signup careers show pages programmes show pages
Added dynamic popup
shot A
=> 51 create modals for use in loginsignup careers show pages programmes show pages

app/controllers/programmes_controller.rb, config/routes.rb, db/seeds.rb
Linked subjects to programmes slightly differently in seed file to generate better results. Nested route for programmes index under its related career, so that when users click on the link to view related programmes they only see the careers associated with that programme.
=> 55 associate programmes with subjects

app/assets/stylesheets/components/_popup_form.scss, app/views/programmes/index.html.erb, app/views/shared/_accordion.html.erb, app/views/shared/_career_modal.html.erb
implemented show page for careers. it includes:
1.Job title
2.summary
3.General responsibilities
4. career progression
5. Educational requirements
Please include a summary of the changes and the link to the ticket (jira/canban board etc). Please also include relevant motivation and context. List any dependencies that are required for this change.
=> 28 implement show page for careers

app/controllers/registrations_controller.rb, config/routes.rb
Rerouted after user sign up, to user edit page
=> 58 fix links

app/assets/stylesheets/config/_fonts.scss, app/views/devise/registrations/new.html.erb, app/views/devise/sessions/new.html.erb, app/views/shared/_navbar.html.erb
Navbar was missing a sign up page and log in /sign up pages were unstyled. Fixed both problems.
=> 64 add sign up to navbar and styled log in / sign up

app/assets/stylesheets/components/_accordion.scss, app/assets/stylesheets/components/_banners.scss, app/assets/stylesheets/components/_popup_form.scss, app/views/programmes/index.html.erb, app/views/shared/_accordion.html.erb, app/views/shared/_career_modal.html.erb, app/views/shared/_programme_modal.erb
Edited some styling for both career and programme modals
=> 41 implement show page for programmes

app/controllers/pathways_controller.rb, app/models/user.rb
Removed reference to primary pathways in user model
=> removed refernce to active pathways in user model

app/controllers/pathways_controller.rb
Removed typo from pathways controller.
=> removed typo from pathways controller

Gemfile, Gemfile.lock, app/assets/stylesheets/application.scss, app/controllers/pages_controller.rb, app/models/event.rb, app/models/pathway.rb, app/models/programme.rb, app/models/user.rb, app/views/pages/dashboard.html.erb, app/views/pages/home.html.erb, app/views/pathways/create.json.jbuilder, config/routes.rb, db/migrate/20230327032929_create_event.rb, db/schema.rb, db/seeds.rb
1. Install calendar gem
2. Set up events model
3. Set up dashboard controller action (pages#dashboard)
4. Set up dashboard view and render events tagged to user's programmes on calendar, complete with pagination (sort by month).
=> Events Calendar

app/assets/stylesheets/components/_accordion.scss, app/assets/stylesheets/components/_buttons.scss, app/assets/stylesheets/components/_index.scss, app/javascript/controllers/shortlist_controller.js, app/models/programme.rb, app/views/pathways/create.json.jbuilder, app/views/programmes/index.html.erb, db/schema.rb
Some styles were left in programmes index, so they are moved to CSS. Shortlist code refactored.
=> Clean up styles and refactor code

app/assets/stylesheets/components/_banners.scss, app/views/pages/home.html.erb
Reduced horizontal margin in hero banner so text is aligned better.
=> Adjust hero banner spacing

app/views/programmes/index.html.erb, app/views/shared/_navbar.html.erb
Added navbar links for careers and dashboard
=>  navbar links

app/assets/stylesheets/components/_countdown.scss, app/assets/stylesheets/components/_simple_calendar.scss, app/controllers/pages_controller.rb, app/views/pages/dashboard.html.erb, app/views/shared/_countdown.html.erb
Added spacing around cards in dashboard.
=> 118 space elements out on dashboard

app/assets/stylesheets/components/_backgrounds.scss, app/views/pathways/index.html.erb, app/views/shared/_footer.html.erb
Fixed footer to the bottom of all pages and centered card in pathways page
=> Fix footer at bottom and center card

app/assets/stylesheets/config/_fonts.scss, app/views/pages/home.html.erb
=> Adjust font weights, edit copy, add footer padding

app/views/pathways/_pathway.html.erb
=> Adjust font weights of pathways

app/assets/stylesheets/components/_backgrounds.scss, app/views/pathways/index.html.erb, app/views/shared/_footer.html.erb
Multiple pages are being cut off by fixed footer. Let's change the footer position on selected pages as needed, instead of sitewide.
Reverts jwltay/my_pathways_future#141
=> Revert "Fix footer at bottom and center card"

app/assets/stylesheets/components/_accordion.scss, app/controllers/programmes_controller.rb, app/views/careers/index.html.erb, app/views/programmes/index.html.erb
Split programme accordion into two side by side accordions so they can expand independently.
=> 155 fix programme accordion

app/assets/stylesheets/config/_fonts.scss
Please include a summary of the changes and the link to the ticket (jira/canban board etc). Please also include relevant motivation and context. List any dependencies that are required for this change.
=> updated font imports
